name: Deploy to Firebase Hosting on Push

on:
  push:
    branches:
      - main # Change this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase Hosting
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --project global-connect-7c86b --token "${{ secrets.FIREBASE_TOKEN }}"
